import java.util.*;
        
public class PythonProjects {
    
/*
 * #****************************************************************************
#                          CntRandNbrs.PY
#
#  Generate an arbitrary number of random numbers between 1 and 10 inclusive.
#  Count how many times each random number is generated by the random number
#  generator.
#
#  Your code must use "while" statements, "if elif" statements, counters, other
#  variables, and any other Python statements needed to complete the assignment.
#
#  Use meaningful variable names. Clearly indent code and add white space
#  to separate/group related items. Make sure your code is readable.
#
#  After generating the random numbers print the results in the following
#  format: 
#
#  Value (1) - 15
#  Value (2) - 35
#  Value (3) - 7
#     ...etc...
#  Value (10) - 25
#
#
#****************************************************************************
 */
    
    public void python1() 
    {
        /*
        Scanner n = new Scanner(System.in);
        System.out.print("Please enter a value: ");
        int numbn = n.nextInt();
        System.out.println();
        System.out.println("This was your number: " + numbn);
        */
        int one = 0;
        int two = 0;
        int three = 0;
        int four = 0;
        int five = 0;
        int six = 0;
        int seven = 0;
        int eight = 0;
        int nine = 0;
        int ten = 0;
        int[] rnd = new int[100];
        for (int i = 0; i < 100; i++) 
        {
            rnd[i] = ((int)(Math.random() * 10)) + 1;
        }
        for (int i = 0; i < 100; i++)
        {
            if (rnd[i] == 1) 
            {
                one++;
            }
            if (rnd[i] == 2) 
            {
                two++;
            }
             if (rnd[i] == 3) 
            {
                three++;
            }
            if (rnd[i] == 4) 
            {
                four++;
            } 
            if (rnd[i] == 5) 
            {
                five++;
            }
            if (rnd[i] == 6) 
            {
                six++;
            } 
            if (rnd[i] == 7) 
            {
                seven++;
            }
            if (rnd[i] == 8) 
            {
                eight++;
            } 
            if (rnd[i] == 9) 
            {
                nine++;
            }
            if (rnd[i] == 10) 
            {
                ten++;
            }
        }
        System.out.println("Value (1) - " + one);
        System.out.println("Value (2) - " + two);
        System.out.println("Value (3) - " + three);
        System.out.println("Value (4) - " + four);
        System.out.println("Value (5) - " + five);
        System.out.println("Value (6) - " + six);
        System.out.println("Value (7) - " + seven);
        System.out.println("Value (8) - " + eight);
        System.out.println("Value (9) - " + nine);
        System.out.println("Value (10) - " + ten);
    }
    
/*
    #****************************************************************************
#                          CntOddEvenNbrs.PY
#
# Generate an arbitrary number of random numbers between a minVal and MaxVal.
#
# Count the number of even and odd numbers generated. Also determine the
# largest and smallest generated odd and even numbers. 
#
# You program should generate the following report....
#
# Even numbers generated: 
# Largest even number: 
# Smallest even number:
#
# Odd numbers generated: 
# Largest odd number: 
# Smallest odd number:
#
#****************************************************************************

*/
    
    public void python2(int minVal, int MaxVal) 
    {
        int even = 0;
        int odd = 0;
        int scale = MaxVal - minVal + 1;
        int[] randn = new int[100];
        for (int i = 0; i < 100; i++)
        {
            randn[i] = ((int)(Math.random() * scale)) + minVal;
        }
        int emax = minVal - 1;
        int emin = MaxVal + 1; 
        int omax = minVal - 1; 
        int omin = MaxVal + 1; 
        for (int i =0; i < 100; i++)
        {
            if (randn[i] % 2 == 0) 
            {
                even++;
                if (randn[i] > emax) 
                {
                    emax = randn[i];
                }
                if (randn[i] < emin) 
                {
                    emin = randn[i];
                }
            }
            if (randn[i] % 2 != 0) 
            {
                odd++;
                if (randn[i] > omax) 
                {
                    omax = randn[i];
                }
                if (randn[i] < omin) 
                {
                    omin = randn[i];
                }
            }
        }
        System.out.println("Even numbers generated: " + even);
        System.out.println("Largest even number: " + emax);
        System.out.println("Smallest even number: " + emin);
        System.out.println();
        System.out.println("Odd numbers generated: " + odd);
        System.out.println("Largest odd number: " + omax);
        System.out.println("Smallest odd number: " + omin);
    }
    
/*
#****************************************************************************
#                          MakeFactors.PY
# Prompt a user to enter a number. Print out all factors of the number input
# by the user. Create user interface given below:
#
#Example:
#
#
#   FACTOR GENERATOR 
#
# Please enter a number --> 18
#
# The factors of 18 are 1, 2, 3, 6, 9, 18.
#
#
#
#****************************************************************************
*/
    
    public void python3() 
    {
        Scanner input = new Scanner(System.in);
        System.out.println("FACTOR GENERATOR");
        System.out.println();
        System.out.print("Please enter a number --> ");
        System.out.println();
        int numbn = input.nextInt();
        input.close();
        String output = "The factors of " + numbn + " are ";
        for (int i = 1; i < numbn; i++)
        {
            if (numbn % i == 0) 
            {
                output = output + i + ", ";
            }
        }
        output = output + numbn + ".";
        System.out.println(output);
    }
/*
#****************************************************************************    
#                        GuessMyPhrase.PY
# 
# Prompt a user to play a phrase guess game. The computer will allow you
# an arbitrary number of guesses. A sample session for the word "bagel"
# would proceed as follows.
#
#  Welcome to Guess My Phrase
#  Would you like to Play? enter yes \ no -->
#
#  You selected yes. I will give you 8 guesses.
#  My phrase contains 1 word 5 letters.
#  You can enter a word or a letter for each guess.
#
#  Guess #1 --> b
#  b is correct
#  correct guesses: b
#  incorrect guesses: 
#
#  Guess #2 --> w
#  w is not correct
#  correct guesses: b
#  incorrect guesses: w
#
#  Guess #3 --> t
#  t is not correct
#  correct guesse b 
#  incorrect guesses: w, t
#
#  Guess #4 --> a
#  a is correct
#  correct guesses: b, a 
#  incorrect guesses: w, t
#  
#  Guess #5 --> e
#  e is correct
#  correct guesses: b, a, e 
#  incorrect guesses: w, t
#
#
# The game should be ended with one of the following phrases. 
#
# Congratulations! You have guessed all the letters in my phrase.
# Congratulations! You have guessed my phrase!
# Sorry. Game Over. You have used all your Guesses.
# Thank You. Play Again Soon!
#****************************************************************************
*/
    
    public void python4() 
    {
        System.out.println("\nWeclome to Guess My Phrase! \nWould you like to play (yes / no)? --> ");
        Scanner yn = new Scanner(System.in);
        String dec = yn.next();
        char[] cguess= new char[26];
        String right = "";
        String wrong = "";
        boolean wguess = false;
        char[] iguess= new char[26];
        String word = "bagel";
        int guesses = 10;
        boolean repeat = false;
        if (dec.equals("yes")) 
        {
            System.out.println("\nYou selected yes. I will give you "+guesses+" guesses.\nMy phrase contains 1 word and "+word.length()+" letters.\nYou can enter a word or a letter for each guess.\n");
            boolean won = false;
            int g = 0;
            while (won == false)
            {
                g++;
                boolean subtrue = false;
                repeat = false;
                boolean correct = false;
                System.out.println("Guess "+(g)+" --> ");
                String guess = yn.next();
                int place = -1;
                if (guess.length() == 1) 
                {
                    for (int i = 0; i < (word.length()); i++) 
                    {
                        if (word.substring(i, i+1).equals(guess))
                        {
                            subtrue = true;
                            System.out.println("\n"+guess+" is correct");
                            for (int h = 0; h < cguess.length; h++) 
                            {
                                if (cguess[h] == '\0')
                                {
                                    place = h;
                                    break;
                                }
                                else {}
                            }
                            for (int h = 0; h < cguess.length; h++) 
                            {
                                if (cguess[h] == guess.charAt(0))
                                {
                                    repeat = true;
                                    g--;
                                }
                                else {}
                            }
                            if (repeat != true) 
                            {
                                cguess[place] = guess.charAt(0);
                                if (right.length() == 0)
                                {
                                    right = right + guess;
                                }
                                else
                                {
                                    right = right + ", " + guess;
                                }
                            }
                        }
                    }
                    if (subtrue != true) 
                    {
                        System.out.println("\n"+guess+" is incorrect");
                        for (int h = 0; h < iguess.length; h++) 
                            {
                                if (cguess[h] == '\0')
                                {
                                    place = h;
                                    break;
                                }
                                else {}
                            }
                            for (int h = 0; h < cguess.length; h++) 
                            {
                                if (cguess[h] == guess.charAt(0))
                                {
                                    repeat = true;
                                    g--;
                                }
                                else {}
                            }
                            if (repeat != true) 
                            {
                                iguess[place] = guess.charAt(0);
                                if (wrong.length() == 0)
                                {
                                    wrong = wrong + guess;
                                }
                                else
                                {
                                    wrong = wrong + ", " + guess;
                                }
                            }
                    } 
                    System.out.println("Correct guesses: " + right);
                    System.out.println("Incorrect guesses: " + wrong + "\n");
                }
                else 
                {
                    if(guess.equals(word))
                    {
                        won = true;
                        System.out.println();
                    }
                    else
                    {
                        g = guesses;
                        wguess = true;
                    }
                }
                if (cguess[word.length() - 1] != '\0')
                {
                    won = true;
                }
                if (g >= guesses)
                {
                    break;
                }

            }
            if (won == true) 
            {
                System.out.println("Congratulations! You won! The word was: " + word);
                System.out.println("Thank You. Play Again Soon!\n");
            }
            if (won == false && wguess == false) 
            {
                System.out.println("Sorry. Game Over. You have used all your guesses.");
                System.out.println("Thank You. Play Again Soon!\n");
            }
            if (won == false && wguess == true) 
            {
                System.out.println("\nSorry. Game Over. You have guessed incorrectly.");
                System.out.println("Thank You. Play Again Soon!\n");
            }
        }
        else
        {
            System.out.println("See you later!");
        }
        yn.close();
    }
}
